name: ensembles-labs
dependencies:
  - jupyter=1.0.*
  - matplotlib=3.3.*
  - pandas=1.2.*
  - pip=21.0.*
  - py-xgboost=1.5.*
  - scikit-learn=1.0.*
  - seaborn=0.11.*
  - tornado=6.0.2
  - pip:
    - shap==0.40.*
